[package]
name = "lemmy-search"
version = "0.0.1"
edition = "2021"
authors = ["MarSara9"]

[dependencies]
serde = { version = "1.0.*", features = ["derive"] }
reqwest = { version = "0.11.*", features = ["json"] }
tokio = { version = "1.28.*", features = ["rt-multi-thread"] }
actix-web = "4.3.*"
actix-files = "0.6.*"
postgres = "0.19.*"
async-std = "1.12.*"
futures = "0.3.*"
