[package]
name = "lemmy-search"
version = "0.1.0"
edition = "2021"
authors = ["MarSara9"]

[dependencies]
async-trait = "0.1.*"
lazy_static = "1.4.*"
url = { version = "2.4.*", features = ["serde"] }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = { version = "1.0.*", features = ["default"] }
reqwest = { version = "0.11.*", features = ["json"] }
tokio = { version = "1.28.*", features = ["rt-multi-thread"] }
actix-web = { version = "4.3.*", features = ["macros", "compress-gzip", "cookies"] }
actix-files = "0.6.*"
async-std = { version = "1.12.*", features = ["std"] }
futures = { version = "0.3.*", features = ["std", "async-await", "executor"] }
clokwerk = "0.4.*"
chrono = { version = "0.4.*", features = ["std"] }
config-file = { version = "0.2.3", features = ["yaml"] }
uuid = { version = "1.3.*", features = ["v4"] }
postgres = { version = "0.19.*", features = ["with-uuid-1", "with-chrono-0_4"] }
r2d2_postgres = {version = "0.18.*", features = [] }
regex = { version  = "1.8.*", features = ["std"] }