[package]
name = "lemmy-search"
version = "0.0.1"
edition = "2021"
authors = ["MarSara9"]

[dependencies]
serde = { version = "1.0.*", features = ["derive"] }
reqwest = { version = "0.11.*", features = ["json"] }
tokio = { version = "1.28.*", features = ["rt-multi-thread"] }
actix-web = { version = "4.3.*", features = ["macros", "compress-gzip", "cookies"] }
actix-files = "0.6.*"
async-std = { version = "1.12.*", features = ["std"] }
futures = { version = "0.3.*", features = ["std", "async-await", "executor"] }
clokwerk = "0.4.*"
chrono = { version = "0.4.*", features = ["std"] }
config-file = { version = "0.2.3", features = ["yaml"] }
postgres = "0.19.*"
r2d2_postgres = {version = "0.18.*", features = [] }