name: docker build develop
run-name: ${{ github.actor }} is building and pushing to docker-hub.
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'server/**'
      - 'ui/**'
      - 'docker/dev.dockerfile'
      - 'Cargo.toml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    env:
      DOCKER_FILE: 'docker/dev.dockerfile'
      DOCKER_TAG: 'marsara9/lemmy-search:dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{env.DOCKER_FILE}}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{env.DOCKER_TAG}}

      # - uses: meeDamian/sync-readme@v1.0.6
      #   with:
      #     pass: ${{ secrets.DOCKERHUB_TOKEN }}
      #     description: true